### ISSUE TITLE
Can't find _hash_encoder module

### ISSUE THREAD

**Issue by ggxxii** [songrise/AvatarCraft#8]
This is the error:
<img width="709" alt="image" src="https://github.com/songrise/AvatarCraft/assets/118959821/91115687-726e-4e05-b298-3e3765a9900c">
Env:
CUDA11.3+pytorch1.12.0+pytorch3D 0.7.4+nvidia cub 1.11.0

**Comment by ggxxii** [comment]
BTW, I am running on Windows, please help

**Comment by songrise** [comment]
Hi, thanks for your interset in this project. I don't have a Windows server and cannot reproduce this issue. I did not encounter this issue on Linux. From the log I can see that the issue is related to the custum CUDA operator, and the implementation borrowed from [instant-nsr](https://github.com/zhaofuq/Instant-NSR). You may create a issue there.

**Comment by ggxxii** [comment]
Thx for the quick response, I'm changing to Linux now LOL.
